module: dylan-user
copyright: See LICENSE file in this distribution.

define library gdkpixbuf
  use dylan;
  use common-dylan;
  use c-ffi;
  use gio;
  use gobject;
  use gmodule;
  use glib;

  export gdkpixbuf;
  export gdkpixbuf-properties;
end library;

define module gdkpixbuf
  use dylan;
  use common-dylan;
  use c-ffi;
  use gio;
  use gobject;
  use gobject-glue;
  use gmodule;
  use glib;

  export
    gdk-pixbuf-error-quark,
    <GdkPixbufSimpleAnimIter*>,
    <GdkPixbufSimpleAnimIter>,
    <GdkPixbufSimpleAnimClass>,
    gdk-pixbuf-simple-anim-set-loop,
    gdk-pixbuf-simple-anim-get-loop,
    gdk-pixbuf-simple-anim-add-frame,
    gdk-pixbuf-simple-anim-new,
    <GdkPixbufSimpleAnim*>,
    <GdkPixbufSimpleAnim>,
    <GdkPixbufRotation*>,
    <GdkPixbufRotation>,
    $gdk-pixbuf-rotate-clockwise,
    $gdk-pixbuf-rotate-upsidedown,
    $gdk-pixbuf-rotate-counterclockwise,
    $gdk-pixbuf-rotate-none,
    gdk-pixbuf-non-anim-new,
    <GdkPixbufNonAnim*>,
    <GdkPixbufNonAnim>,
    gdk-pixbuf-module-pattern-relevance-setter,
    gdk-pixbuf-module-pattern-relevance,
    gdk-pixbuf-module-pattern-mask-setter,
    gdk-pixbuf-module-pattern-mask,
    gdk-pixbuf-module-pattern-prefix-setter,
    gdk-pixbuf-module-pattern-prefix,
    <GdkPixbufModulePattern>,
    gdk-pixbuf-module-_reserved4,
    gdk-pixbuf-module-_reserved3,
    gdk-pixbuf-module-_reserved2,
    gdk-pixbuf-module-_reserved1,
    gdk-pixbuf-module-is-save-option-supported-setter,
    gdk-pixbuf-module-is-save-option-supported,
    gdk-pixbuf-module-save-to-callback-setter,
    gdk-pixbuf-module-save-to-callback,
    gdk-pixbuf-module-save-setter,
    gdk-pixbuf-module-save,
    gdk-pixbuf-module-load-animation-setter,
    gdk-pixbuf-module-load-animation,
    gdk-pixbuf-module-load-increment-setter,
    gdk-pixbuf-module-load-increment,
    gdk-pixbuf-module-stop-load-setter,
    gdk-pixbuf-module-stop-load,
    gdk-pixbuf-module-begin-load-setter,
    gdk-pixbuf-module-begin-load,
    gdk-pixbuf-module-load-xpm-data-setter,
    gdk-pixbuf-module-load-xpm-data,
    gdk-pixbuf-module-load-setter,
    gdk-pixbuf-module-load,
    gdk-pixbuf-module-info-setter,
    gdk-pixbuf-module-info,
    gdk-pixbuf-module-module-setter,
    gdk-pixbuf-module-module,
    gdk-pixbuf-module-module-path-setter,
    gdk-pixbuf-module-module-path,
    gdk-pixbuf-module-module-name-setter,
    gdk-pixbuf-module-module-name,
    <GdkPixbufModule>,
    gdk-pixbuf-loader-class-closed,
    gdk-pixbuf-loader-class-area-updated,
    gdk-pixbuf-loader-class-area-prepared,
    gdk-pixbuf-loader-class-size-prepared,
    gdk-pixbuf-loader-class-parent-class,
    <GdkPixbufLoaderClass>,
    gdk-pixbuf-loader-write-bytes,
    gdk-pixbuf-loader-write,
    gdk-pixbuf-loader-set-size,
    gdk-pixbuf-loader-get-pixbuf,
    gdk-pixbuf-loader-get-format,
    gdk-pixbuf-loader-get-animation,
    gdk-pixbuf-loader-close,
    gdk-pixbuf-loader-new-with-type,
    gdk-pixbuf-loader-new-with-mime-type,
    gdk-pixbuf-loader-new,
    <GdkPixbufLoader*>,
    <GdkPixbufLoader>,
    <GdkPixbufFormatFlags*>,
    <GdkPixbufFormatFlags>,
    $gdk-pixbuf-format-threadsafe,
    $gdk-pixbuf-format-scalable,
    $gdk-pixbuf-format-writable,
    gdk-pixbuf-format-set-disabled,
    gdk-pixbuf-format-is-writable,
    gdk-pixbuf-format-is-scalable,
    gdk-pixbuf-format-is-save-option-supported,
    gdk-pixbuf-format-is-disabled,
    gdk-pixbuf-format-get-name,
    gdk-pixbuf-format-get-mime-types,
    gdk-pixbuf-format-get-license,
    gdk-pixbuf-format-get-extensions,
    gdk-pixbuf-format-get-description,
    gdk-pixbuf-format-free,
    gdk-pixbuf-format-copy,
    gdk-pixbuf-format-license-setter,
    gdk-pixbuf-format-license,
    gdk-pixbuf-format-disabled-setter,
    gdk-pixbuf-format-disabled,
    gdk-pixbuf-format-flags-setter,
    gdk-pixbuf-format-flags,
    gdk-pixbuf-format-extensions-setter,
    gdk-pixbuf-format-extensions,
    gdk-pixbuf-format-mime-types-setter,
    gdk-pixbuf-format-mime-types,
    gdk-pixbuf-format-description-setter,
    gdk-pixbuf-format-description,
    gdk-pixbuf-format-domain-setter,
    gdk-pixbuf-format-domain,
    gdk-pixbuf-format-signature-setter,
    gdk-pixbuf-format-signature,
    gdk-pixbuf-format-name-setter,
    gdk-pixbuf-format-name,
    <GdkPixbufFormat>,
    <GdkPixbufError*>,
    <GdkPixbufError>,
    $gdk-pixbuf-error-incomplete-animation,
    $gdk-pixbuf-error-failed,
    $gdk-pixbuf-error-unsupported-operation,
    $gdk-pixbuf-error-unknown-type,
    $gdk-pixbuf-error-bad-option,
    $gdk-pixbuf-error-insufficient-memory,
    $gdk-pixbuf-error-corrupt-image,
    gdk-pixbuf-animation-iter-class-advance,
    gdk-pixbuf-animation-iter-class-on-currently-loading-frame,
    gdk-pixbuf-animation-iter-class-get-pixbuf,
    gdk-pixbuf-animation-iter-class-get-delay-time,
    gdk-pixbuf-animation-iter-class-parent-class,
    <GdkPixbufAnimationIterClass>,
    gdk-pixbuf-animation-iter-on-currently-loading-frame,
    gdk-pixbuf-animation-iter-get-pixbuf,
    gdk-pixbuf-animation-iter-get-delay-time,
    gdk-pixbuf-animation-iter-advance,
    <GdkPixbufAnimationIter*>,
    <GdkPixbufAnimationIter>,
    gdk-pixbuf-animation-class-get-iter,
    gdk-pixbuf-animation-class-get-size,
    gdk-pixbuf-animation-class-get-static-image,
    gdk-pixbuf-animation-class-is-static-image,
    gdk-pixbuf-animation-class-parent-class,
    <GdkPixbufAnimationClass>,
    gdk-pixbuf-animation-is-static-image,
    gdk-pixbuf-animation-get-width,
    gdk-pixbuf-animation-get-static-image,
    gdk-pixbuf-animation-get-iter,
    gdk-pixbuf-animation-get-height,
    gdk-pixbuf-animation-new-from-stream-async,
    gdk-pixbuf-animation-new-from-stream-finish,
    gdk-pixbuf-animation-new-from-stream,
    gdk-pixbuf-animation-new-from-resource,
    gdk-pixbuf-animation-new-from-file,
    <GdkPixbufAnimation*>,
    <GdkPixbufAnimation>,
    gdk-pixbuf-set-option,
    gdk-pixbuf-scale-simple,
    gdk-pixbuf-scale,
    gdk-pixbuf-savev,
    gdk-pixbuf-save-to-streamv-async,
    gdk-pixbuf-save-to-streamv,
    gdk-pixbuf-save-to-callbackv,
    gdk-pixbuf-save-to-bufferv,
    gdk-pixbuf-saturate-and-pixelate,
    gdk-pixbuf-rotate-simple,
    gdk-pixbuf-remove-option,
    gdk-pixbuf-read-pixels,
    gdk-pixbuf-read-pixel-bytes,
    gdk-pixbuf-new-subpixbuf,
    gdk-pixbuf-get-width,
    gdk-pixbuf-get-rowstride,
    gdk-pixbuf-get-pixels-with-length,
    gdk-pixbuf-get-options,
    gdk-pixbuf-get-option,
    gdk-pixbuf-get-n-channels,
    gdk-pixbuf-get-height,
    gdk-pixbuf-get-has-alpha,
    gdk-pixbuf-get-colorspace,
    gdk-pixbuf-get-byte-length,
    gdk-pixbuf-get-bits-per-sample,
    gdk-pixbuf-flip,
    gdk-pixbuf-fill,
    gdk-pixbuf-copy-options,
    gdk-pixbuf-copy-area,
    gdk-pixbuf-copy,
    gdk-pixbuf-composite-color-simple,
    gdk-pixbuf-composite-color,
    gdk-pixbuf-composite,
    gdk-pixbuf-apply-embedded-orientation,
    gdk-pixbuf-add-alpha,
    gdk-pixbuf-save-to-stream-finish,
    gdk-pixbuf-new-from-stream-at-scale-async,
    gdk-pixbuf-new-from-stream-async,
    gdk-pixbuf-init-modules,
    gdk-pixbuf-get-formats,
    gdk-pixbuf-get-file-info-finish,
    gdk-pixbuf-get-file-info-async,
    gdk-pixbuf-get-file-info,
    gdk-pixbuf-calculate-rowstride,
    gdk-pixbuf-new-from-xpm-data,
    gdk-pixbuf-new-from-stream-finish,
    gdk-pixbuf-new-from-stream-at-scale,
    gdk-pixbuf-new-from-stream,
    gdk-pixbuf-new-from-resource-at-scale,
    gdk-pixbuf-new-from-resource,
    gdk-pixbuf-new-from-file-at-size,
    gdk-pixbuf-new-from-file-at-scale,
    gdk-pixbuf-new-from-file,
    gdk-pixbuf-new-from-data,
    gdk-pixbuf-new-from-bytes,
    gdk-pixbuf-new,
    <GdkPixbuf*>,
    <GdkPixbuf>,
    $pixbuf-version,
    $pixbuf-minor,
    $pixbuf-micro,
    $pixbuf-major,
    <GdkInterpType*>,
    <GdkInterpType>,
    $gdk-interp-hyper,
    $gdk-interp-bilinear,
    $gdk-interp-tiles,
    $gdk-interp-nearest,
    <GdkColorspace*>,
    <GdkColorspace>,
    $gdk-colorspace-rgb;
end module;

define module gdkpixbuf-properties
  use gdkpixbuf;
  use gobject-glue;

  export
    @loop-setter,
    @loop,
    @width-setter,
    @width,
    @rowstride-setter,
    @rowstride,
    @pixels-setter,
    @pixels,
    @pixel-bytes-setter,
    @pixel-bytes,
    @n-channels-setter,
    @n-channels,
    @height-setter,
    @height,
    @has-alpha-setter,
    @has-alpha,
    @colorspace-setter,
    @colorspace,
    @bits-per-sample-setter,
    @bits-per-sample;
end module;
