module: dylan-user
copyright: See LICENSE file in this distribution.

define library gsk
  use dylan;
  use common-dylan;
  use c-ffi;
  use gmodule;
  use gdkpixbuf;
  use pango;
  use cairo;
  use gio;
  use gdk;
  use graphene;
  use glib;
  use gobject;

  export gsk;
  export gsk-properties;
end library;

define module gsk
  use dylan;
  use common-dylan;
  use c-ffi;
  use gmodule;
  use gdkpixbuf;
  use pango;
  use cairo;
  use gio;
  use gdk;
  use graphene;
  use glib;
  use gobject;
  use gobject-glue;

  export
    gsk-value-take-render-node,
    gsk-value-set-render-node,
    gsk-value-get-render-node,
    gsk-value-dup-render-node,
    gsk-serialization-error-quark,
    gsk-transform-node-get-transform,
    gsk-transform-node-get-child,
    gsk-transform-node-new,
    <GskTransformNode*>,
    <GskTransformNode>,
    <GskTransformCategory*>,
    <GskTransformCategory>,
    $gsk-transform-category-identity,
    $gsk-transform-category-2d-translate,
    $gsk-transform-category-2d-affine,
    $gsk-transform-category-2d,
    $gsk-transform-category-3d,
    $gsk-transform-category-any,
    $gsk-transform-category-unknown,
    gsk-transform-parse,
    gsk-transform-unref,
    gsk-transform-translate-3d,
    gsk-transform-translate,
    gsk-transform-transform-point,
    gsk-transform-transform-bounds,
    gsk-transform-transform,
    gsk-transform-to-translate,
    gsk-transform-to-string,
    gsk-transform-to-matrix,
    gsk-transform-to-affine,
    gsk-transform-to-2d-components,
    gsk-transform-to-2d,
    gsk-transform-skew,
    gsk-transform-scale-3d,
    gsk-transform-scale,
    gsk-transform-rotate-3d,
    gsk-transform-rotate,
    gsk-transform-ref,
    gsk-transform-print,
    gsk-transform-perspective,
    gsk-transform-matrix,
    gsk-transform-invert,
    gsk-transform-get-category,
    gsk-transform-equal,
    gsk-transform-new,
    <GskTransform>,
    gsk-texture-node-get-texture,
    gsk-texture-node-new,
    <GskTextureNode*>,
    <GskTextureNode>,
    gsk-text-node-has-color-glyphs,
    gsk-text-node-get-offset,
    gsk-text-node-get-num-glyphs,
    gsk-text-node-get-glyphs,
    gsk-text-node-get-font,
    gsk-text-node-get-color,
    gsk-text-node-new,
    <GskTextNode*>,
    <GskTextNode>,
    gsk-shadow-node-get-shadow,
    gsk-shadow-node-get-n-shadows,
    gsk-shadow-node-get-child,
    gsk-shadow-node-new,
    <GskShadowNode*>,
    <GskShadowNode>,
    gsk-shadow-radius-setter,
    gsk-shadow-radius,
    gsk-shadow-dy-setter,
    gsk-shadow-dy,
    gsk-shadow-dx-setter,
    gsk-shadow-dx,
    gsk-shadow-color-setter,
    gsk-shadow-color,
    <GskShadow>,
    gsk-shader-args-builder-unref,
    gsk-shader-args-builder-to-args,
    gsk-shader-args-builder-set-vec4,
    gsk-shader-args-builder-set-vec3,
    gsk-shader-args-builder-set-vec2,
    gsk-shader-args-builder-set-uint,
    gsk-shader-args-builder-set-int,
    gsk-shader-args-builder-set-float,
    gsk-shader-args-builder-set-bool,
    gsk-shader-args-builder-ref,
    gsk-shader-args-builder-new,
    <GskShaderArgsBuilder>,
    <GskSerializationError*>,
    <GskSerializationError>,
    $gsk-serialization-invalid-data,
    $gsk-serialization-unsupported-version,
    $gsk-serialization-unsupported-format,
    <GskScalingFilter*>,
    <GskScalingFilter>,
    $gsk-scaling-filter-trilinear,
    $gsk-scaling-filter-nearest,
    $gsk-scaling-filter-linear,
    gsk-rounded-rect-shrink,
    gsk-rounded-rect-offset,
    gsk-rounded-rect-normalize,
    gsk-rounded-rect-is-rectilinear,
    gsk-rounded-rect-intersects-rect,
    gsk-rounded-rect-init-from-rect,
    gsk-rounded-rect-init-copy,
    gsk-rounded-rect-init,
    gsk-rounded-rect-contains-rect,
    gsk-rounded-rect-contains-point,
    gsk-rounded-rect-corner-setter,
    gsk-rounded-rect-corner,
    gsk-rounded-rect-bounds-setter,
    gsk-rounded-rect-bounds,
    <GskRoundedRect>,
    gsk-rounded-clip-node-get-clip,
    gsk-rounded-clip-node-get-child,
    gsk-rounded-clip-node-new,
    <GskRoundedClipNode*>,
    <GskRoundedClipNode>,
    gsk-repeating-radial-gradient-node-new,
    <GskRepeatingRadialGradientNode*>,
    <GskRepeatingRadialGradientNode>,
    gsk-repeating-linear-gradient-node-new,
    <GskRepeatingLinearGradientNode*>,
    <GskRepeatingLinearGradientNode>,
    gsk-repeat-node-get-child-bounds,
    gsk-repeat-node-get-child,
    gsk-repeat-node-new,
    <GskRepeatNode*>,
    <GskRepeatNode>,
    <GskRendererClass>,
    gsk-renderer-unrealize,
    gsk-renderer-render-texture,
    gsk-renderer-render,
    gsk-renderer-realize,
    gsk-renderer-is-realized,
    gsk-renderer-get-surface,
    gsk-renderer-new-for-surface,
    <GskRenderer*>,
    <GskRenderer>,
    <GskRenderNodeType*>,
    <GskRenderNodeType>,
    $gsk-gl-shader-node,
    $gsk-debug-node,
    $gsk-blur-node,
    $gsk-text-node,
    $gsk-cross-fade-node,
    $gsk-blend-node,
    $gsk-shadow-node,
    $gsk-rounded-clip-node,
    $gsk-clip-node,
    $gsk-repeat-node,
    $gsk-color-matrix-node,
    $gsk-opacity-node,
    $gsk-transform-node,
    $gsk-outset-shadow-node,
    $gsk-inset-shadow-node,
    $gsk-texture-node,
    $gsk-border-node,
    $gsk-conic-gradient-node,
    $gsk-repeating-radial-gradient-node,
    $gsk-radial-gradient-node,
    $gsk-repeating-linear-gradient-node,
    $gsk-linear-gradient-node,
    $gsk-color-node,
    $gsk-cairo-node,
    $gsk-container-node,
    $gsk-not-a-render-node,
    gsk-render-node-write-to-file,
    gsk-render-node-unref,
    gsk-render-node-serialize,
    gsk-render-node-ref,
    gsk-render-node-get-node-type,
    gsk-render-node-get-bounds,
    gsk-render-node-draw,
    gsk-render-node-deserialize,
    <GskRenderNode*>,
    <GskRenderNode>,
    gsk-radial-gradient-node-get-vradius,
    gsk-radial-gradient-node-get-start,
    gsk-radial-gradient-node-get-n-color-stops,
    gsk-radial-gradient-node-get-hradius,
    gsk-radial-gradient-node-get-end,
    gsk-radial-gradient-node-get-color-stops,
    gsk-radial-gradient-node-get-center,
    gsk-radial-gradient-node-new,
    <GskRadialGradientNode*>,
    <GskRadialGradientNode>,
    gsk-parse-location-line-chars-setter,
    gsk-parse-location-line-chars,
    gsk-parse-location-line-bytes-setter,
    gsk-parse-location-line-bytes,
    gsk-parse-location-lines-setter,
    gsk-parse-location-lines,
    gsk-parse-location-chars-setter,
    gsk-parse-location-chars,
    gsk-parse-location-bytes-setter,
    gsk-parse-location-bytes,
    <GskParseLocation>,
    gsk-outset-shadow-node-get-spread,
    gsk-outset-shadow-node-get-outline,
    gsk-outset-shadow-node-get-dy,
    gsk-outset-shadow-node-get-dx,
    gsk-outset-shadow-node-get-color,
    gsk-outset-shadow-node-get-blur-radius,
    gsk-outset-shadow-node-new,
    <GskOutsetShadowNode*>,
    <GskOutsetShadowNode>,
    gsk-opacity-node-get-opacity,
    gsk-opacity-node-get-child,
    gsk-opacity-node-new,
    <GskOpacityNode*>,
    <GskOpacityNode>,
    <GskNglRenderer*>,
    <GskNglRenderer>,
    gsk-linear-gradient-node-get-start,
    gsk-linear-gradient-node-get-n-color-stops,
    gsk-linear-gradient-node-get-end,
    gsk-linear-gradient-node-get-color-stops,
    gsk-linear-gradient-node-new,
    <GskLinearGradientNode*>,
    <GskLinearGradientNode>,
    gsk-inset-shadow-node-get-spread,
    gsk-inset-shadow-node-get-outline,
    gsk-inset-shadow-node-get-dy,
    gsk-inset-shadow-node-get-dx,
    gsk-inset-shadow-node-get-color,
    gsk-inset-shadow-node-get-blur-radius,
    gsk-inset-shadow-node-new,
    <GskInsetShadowNode*>,
    <GskInsetShadowNode>,
    <GskGLUniformType*>,
    <GskGLUniformType>,
    $gsk-gl-uniform-type-vec4,
    $gsk-gl-uniform-type-vec3,
    $gsk-gl-uniform-type-vec2,
    $gsk-gl-uniform-type-bool,
    $gsk-gl-uniform-type-uint,
    $gsk-gl-uniform-type-int,
    $gsk-gl-uniform-type-float,
    $gsk-gl-uniform-type-none,
    gsk-gl-shader-node-get-shader,
    gsk-gl-shader-node-get-n-children,
    gsk-gl-shader-node-get-child,
    gsk-gl-shader-node-get-args,
    gsk-gl-shader-node-new,
    <GskGLShaderNode*>,
    <GskGLShaderNode>,
    gsk-gl-shader-class-parent-class,
    <GskGLShaderClass>,
    gsk-gl-shader-get-uniform-type,
    gsk-gl-shader-get-uniform-offset,
    gsk-gl-shader-get-uniform-name,
    gsk-gl-shader-get-source,
    gsk-gl-shader-get-resource,
    gsk-gl-shader-get-n-uniforms,
    gsk-gl-shader-get-n-textures,
    gsk-gl-shader-get-args-size,
    gsk-gl-shader-get-arg-vec4,
    gsk-gl-shader-get-arg-vec3,
    gsk-gl-shader-get-arg-vec2,
    gsk-gl-shader-get-arg-uint,
    gsk-gl-shader-get-arg-int,
    gsk-gl-shader-get-arg-float,
    gsk-gl-shader-get-arg-bool,
    gsk-gl-shader-find-uniform-by-name,
    gsk-gl-shader-compile,
    gsk-gl-shader-new-from-resource,
    gsk-gl-shader-new-from-bytes,
    <GskGLShader*>,
    <GskGLShader>,
    <GskGLRendererClass>,
    gsk-gl-renderer-new,
    <GskGLRenderer*>,
    <GskGLRenderer>,
    gsk-debug-node-get-message,
    gsk-debug-node-get-child,
    gsk-debug-node-new,
    <GskDebugNode*>,
    <GskDebugNode>,
    gsk-cross-fade-node-get-start-child,
    gsk-cross-fade-node-get-progress,
    gsk-cross-fade-node-get-end-child,
    gsk-cross-fade-node-new,
    <GskCrossFadeNode*>,
    <GskCrossFadeNode>,
    <GskCorner*>,
    <GskCorner>,
    $gsk-corner-bottom-left,
    $gsk-corner-bottom-right,
    $gsk-corner-top-right,
    $gsk-corner-top-left,
    gsk-container-node-get-n-children,
    gsk-container-node-get-child,
    gsk-container-node-new,
    <GskContainerNode*>,
    <GskContainerNode>,
    gsk-conic-gradient-node-get-rotation,
    gsk-conic-gradient-node-get-n-color-stops,
    gsk-conic-gradient-node-get-color-stops,
    gsk-conic-gradient-node-get-center,
    gsk-conic-gradient-node-get-angle,
    gsk-conic-gradient-node-new,
    <GskConicGradientNode*>,
    <GskConicGradientNode>,
    gsk-color-stop-color-setter,
    gsk-color-stop-color,
    gsk-color-stop-offset-setter,
    gsk-color-stop-offset,
    <GskColorStop>,
    gsk-color-node-get-color,
    gsk-color-node-new,
    <GskColorNode*>,
    <GskColorNode>,
    gsk-color-matrix-node-get-color-offset,
    gsk-color-matrix-node-get-color-matrix,
    gsk-color-matrix-node-get-child,
    gsk-color-matrix-node-new,
    <GskColorMatrixNode*>,
    <GskColorMatrixNode>,
    gsk-clip-node-get-clip,
    gsk-clip-node-get-child,
    gsk-clip-node-new,
    <GskClipNode*>,
    <GskClipNode>,
    <GskCairoRendererClass>,
    gsk-cairo-renderer-new,
    <GskCairoRenderer*>,
    <GskCairoRenderer>,
    gsk-cairo-node-get-surface,
    gsk-cairo-node-get-draw-context,
    gsk-cairo-node-new,
    <GskCairoNode*>,
    <GskCairoNode>,
    <GskBroadwayRendererClass>,
    gsk-broadway-renderer-new,
    <GskBroadwayRenderer*>,
    <GskBroadwayRenderer>,
    gsk-border-node-get-widths,
    gsk-border-node-get-outline,
    gsk-border-node-get-colors,
    gsk-border-node-new,
    <GskBorderNode*>,
    <GskBorderNode>,
    gsk-blur-node-get-radius,
    gsk-blur-node-get-child,
    gsk-blur-node-new,
    <GskBlurNode*>,
    <GskBlurNode>,
    gsk-blend-node-get-top-child,
    gsk-blend-node-get-bottom-child,
    gsk-blend-node-get-blend-mode,
    gsk-blend-node-new,
    <GskBlendNode*>,
    <GskBlendNode>,
    <GskBlendMode*>,
    <GskBlendMode>,
    $gsk-blend-mode-luminosity,
    $gsk-blend-mode-saturation,
    $gsk-blend-mode-hue,
    $gsk-blend-mode-color,
    $gsk-blend-mode-exclusion,
    $gsk-blend-mode-difference,
    $gsk-blend-mode-soft-light,
    $gsk-blend-mode-hard-light,
    $gsk-blend-mode-color-burn,
    $gsk-blend-mode-color-dodge,
    $gsk-blend-mode-lighten,
    $gsk-blend-mode-darken,
    $gsk-blend-mode-overlay,
    $gsk-blend-mode-screen,
    $gsk-blend-mode-multiply,
    $gsk-blend-mode-default;
end module;

define module gsk-properties
  use gsk;
  use gobject-glue;

  export
    @surface,
    @realized,
    @source-setter,
    @source,
    @resource-setter,
    @resource;
end module;
